# This is a basic workflow to help you get started with Actions

name: Comments

on:
  issue_comment
  
jobs:
  post-to-slack:
    runs-on: ubuntu-latest
    steps:
      - run: printf "${{toJson(github.event)}}\n"
     
