on:
  pull_request:
    types: [ opened, synchronize ]

name: Generate release

jobs:
  release:
    name: Generate release
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJson(github.event.pull_request) }}
