name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - uses: actions/setup-node@v1.4.3
        with:
          version: 10
          
      - run: npm i -g conventional-changelog
        
      - run: npm version --no-git-tag-version $(git describe --tags --abbrev=0 | cut -d 'v' -f 2)
        
      - id: log
        run: echo "::set-output name=content::$(conventional-changelog -p angular)"
          
      - name: update release
        id: update_release
        uses: tubone24/update_release@v1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          body: ${{ steps.log.outputs.content }}
          
