on: 
  push:
    branches:
      - release

name: Generate release

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          
      - name: Check output parameters
        run: |
          echo "Tag: ${{ steps.release.outputs.tag_name }}"
          echo "Release: ${{ steps.release.outputs.version }}"
